# Generated by Django 5.2.17 on 2026-09-21 11:33

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0001_telegram_link'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramBot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=128)),
                ('token_hash', models.CharField(max_length=64, unique=True)),
                ('bot_id', models.BigIntegerField(default=0)),
                ('bot_username', models.CharField(max_length=64)),
                ('timezone', models.CharField(default='Europe/Moscow', max_length=64)),
                ('digest_hour', models.PositiveSmallIntegerField(default=8, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(23)])),
                ('remind_minutes', models.PositiveSmallIntegerField(default=30, validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(1440)])),
                ('chat_id', models.BigIntegerField(blank=True, null=True, unique=True)),
                ('telegram_user_id', models.BigIntegerField(blank=True, null=True)),
                ('telegram_username', models.CharField(blank=True, max_length=64)),
                ('linked_at', models.DateTimeField(blank=True, null=True)),
                ('update_offset', models.BigIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='telegram_bot', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='TelegramBotState',
        ),
        migrations.RemoveField(
            model_name='telegramlinktoken',
            name='user',
        ),
        migrations.DeleteModel(
            name='TelegramLink',
        ),
        migrations.DeleteModel(
            name='TelegramLinkToken',
        ),
    ]
