# Generated by Django 5.2.17 on 2026-09-06 14:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0002_alter_todo_options_alter_todo_completed_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(db_index=True, max_length=255)),
                ('color', models.CharField(db_index=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subtask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(db_index=True, max_length=255)),
                ('completed', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=100, verbose_name='Название')),
                ('kind', models.CharField(choices=[('work', 'работа'), ('personal', 'личное'), ('health', 'здоровье'), ('finance', 'финансы'), ('shopping', 'покупки'), ('home', 'дом'), ('hobby', 'хобби'), ('other', 'другое')], default='other', max_length=16)),
            ],
        ),
        migrations.RemoveIndex(
            model_name='todo',
            name='todos_todo_user_id_76f279_idx',
        ),
        migrations.RemoveField(
            model_name='todo',
            name='completed',
        ),
        migrations.AddField(
            model_name='todo',
            name='due_date',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Срок выполнения задачи'),
        ),
        migrations.AddField(
            model_name='todo',
            name='priority',
            field=models.CharField(choices=[('critical', 'Критический'), ('high', 'Высокий'), ('medium', 'Средний'), ('low', 'Низкий')], default='medium', max_length=16),
        ),
        migrations.AddField(
            model_name='todo',
            name='recurrence',
            field=models.CharField(choices=[('daily', 'ежедневно'), ('weekly', 'каждую неделю'), ('monthly', 'ежемесячно'), ('never', 'никогда')], default='never', max_length=16),
        ),
        migrations.AddField(
            model_name='todo',
            name='status',
            field=models.CharField(choices=[('todo', 'Todo'), ('in_progress', 'In Progress'), ('done', 'Done')], db_index=True, default='todo', max_length=16),
        ),
        migrations.AlterField(
            model_name='todo',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='todos', to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AddField(
            model_name='project',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL, verbose_name='Создатель'),
        ),
        migrations.AddField(
            model_name='todo',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='todos', to='todos.project'),
        ),
        migrations.AddField(
            model_name='subtask',
            name='todo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtasks', to='todos.todo'),
        ),
        migrations.AddField(
            model_name='tag',
            name='user',
            field=models.ForeignKey(blank=True, help_text='Пусто — системный тег; иначе только для этого пользователя.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tags', to=settings.AUTH_USER_MODEL, verbose_name='Владелец'),
        ),
        migrations.AddField(
            model_name='todo',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='todos', to='todos.tag', verbose_name='Теги'),
        ),
        migrations.AddIndex(
            model_name='todo',
            index=models.Index(fields=['user', 'status'], name='todos_todo_user_id_c62cb3_idx'),
        ),
        migrations.AddConstraint(
            model_name='project',
            constraint=models.UniqueConstraint(fields=('user', 'project_name'), name='unique_user_project_name'),
        ),
        migrations.AddConstraint(
            model_name='tag',
            constraint=models.UniqueConstraint(fields=('user', 'tag_name'), name='unique_user_tag_name'),
        ),
    ]
