# Generated by Django 5.2.17 on 2026-09-12 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0010_day_note'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='daynote',
            new_name='todos_dayno_user_id_f85e9b_idx',
            old_name='todos_dayno_user_id_date_idx',
        ),
        migrations.RenameIndex(
            model_name='shiftdayoverride',
            new_name='todos_shift_user_id_90bed8_idx',
            old_name='todos_shift_user_id_date_idx',
        ),
    ]
