# Generated by Django 5.2.17 on 2026-09-14 14:17

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0015_rename_default_shift_layers'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('start_at', models.DateTimeField(db_index=True, verbose_name='Начало')),
                ('end_at', models.DateTimeField(blank=True, null=True, verbose_name='Конец')),
                ('all_day', models.BooleanField(default=False, verbose_name='Весь день')),
                ('recurrence', models.CharField(choices=[('daily', 'ежедневно'), ('weekly', 'каждую неделю'), ('monthly', 'ежемесячно'), ('never', 'никогда')], default='never', max_length=16)),
                ('color', models.CharField(default='#e11d48', max_length=7, verbose_name='Цвет')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['start_at', 'id'],
            },
        ),
        migrations.RenameIndex(
            model_name='shiftdayoverride',
            new_name='todos_shift_layer_i_cd5c4b_idx',
            old_name='todos_shift_layer_i_date_idx',
        ),
        migrations.AlterField(
            model_name='shiftkind',
            name='break_minutes',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(480)], verbose_name='Перерыв, мин'),
        ),
        migrations.AlterField(
            model_name='shiftkind',
            name='duration_hours',
            field=models.DecimalField(decimal_places=2, default=Decimal('8.00'), max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0.25')), django.core.validators.MaxValueValidator(Decimal('24'))], verbose_name='Продолжительность, ч'),
        ),
        migrations.AlterField(
            model_name='shiftkind',
            name='hourly_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Оплата, ₽/ч'),
        ),
        migrations.AddField(
            model_name='event',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to=settings.AUTH_USER_MODEL, verbose_name='Владелец'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['user', 'start_at'], name='todos_event_user_id_23f393_idx'),
        ),
    ]
